### ISSUE TITLE
Passing Object instead of String

### ISSUE THREAD

**Issue by mustafaekim** [edcarroll/ta-json#11]
I didnt observe any method that takes an object and cast to a typed TypeScript object. Should we always pass a string? It seems like I should wrap the js object with JSON.stringify(json) everytime.

**Comment by edcarroll** [comment]
I think I know what you mean - if you have a javascript object and want to cast it to a TS object you can use `deserialize` - [explained here](https://github.com/edcarroll/ta-json#deserializeobjectjsonvalue-typefunction-optionsiparseoptionst). This avoids the need to call `JSON.stringify` every time you want to parse the object 😄

**Comment by mustafaekim** [comment]
It seems like deserialize accepts parameter of type JsonValue. It does not accept parameter of type Object. Am I wrong? If works if I write something like {name: "Mustafa"} but does not work if I do JSON.deserialize<User>(myObject)

**Comment by edcarroll** [comment]
So the `JsonValue` type is essentially a type union of `boolean`, `string`, `number`, `object` and `null` - which is what JSON can be. You'll find you can pass any object to it. I'm going to leave this issue open until I put in the docs a mention as to exactly what `JsonValue` is, so it's a bit more clear 😄

**Comment by edcarroll** [comment]
Hang on sorry - could you show me the error it gives when you pass `myObject`? Also, could you show me your declaration of `myObject`? Missed your bit about it not working!

**Comment by mustafaekim** [comment]
OK, however the first line works, the second does not:

```ts
let toClass = function (json: Object): User {
    (1) return JSON.parse<User>(JSON.stringify(json), User);
    (2) return JSON.deserialize<User>(<JsonValue>json);
}
```

**Comment by edcarroll** [comment]
I see the issue! Will work in a fix tonight.

For now, write `return JSON.deserialize<User>(json as any);`

Let me know if you have any further issues 😄

**Comment by mustafaekim** [comment]
that didnt return an object of type User to me. I dont know if I am missing something. Thanks!

**Comment by edcarroll** [comment]
Doh - I'm being dumb! It's `return JSON.deserialize<User>(json as any, User);`

**Comment by mustafaekim** [comment]
Oh ok, that works. Passing the <User> generic may be enough but I dont know what goes behind. Thank you.

**Comment by edcarroll** [comment]
`2.2.4` now takes type `any`, so you won't have this problem again 😄

**Comment by mustafaekim** [comment]
I think that's better for everyone. Thanks!
