### ISSUE TITLE
Typescript Class to Object

### ISSUE THREAD

**Issue by mustafaekim** [edcarroll/ta-json#14]
Hi, is it possible to transform an instance of a TypeScript class to an instance of Object type?

I know that I can achieve this by first stringifying and then parsing as Object however I wonder if there is a direct method for that.

(Why I need that? Because I want to persist my User into mongoDB with JsonDiscriminatorValues.)

Thanks!

**Comment by edcarroll** [comment]
Hi, I believe `serialize` will do what you want. `JSON.serialize(value:any):any` is how you use it - give it a Typescript class and it will return a plain Javascript object (albeit one that has had the transformations from the decorators already applied).

Let me know if that doesn't fit your use case.
