### ISSUE TITLE
Angular 5 error on using “ta-json” library

### ISSUE THREAD

**Issue by sr-hosseyni** [edcarroll/ta-json#21]
Is [this](https://stackoverflow.com/questions/48344381/angular-5-error-on-using-ta-json-library) error related to ta-json or it's my fault ? or even angular bug ?

**Comment by edcarroll** [comment]
Hi, apologies for my slow reply - it looks like there are multiple `reflect-metadata` packages in your `node_modules`, may be worth setting a path in your tsconfig. Let me know if you're still having the issue.
