### ISSUE TITLE
@JsonConverter with number

### ISSUE THREAD

**Issue by ma-gamp** [edcarroll/ta-json#6]
Is it really possible to use the converter with a string as shown in your example? 
I'm asking because of these lines:
```javascript
const primitive = definition.type === String || definition.type === Boolean || definition.type === Number;
```
and
```javascript
   if (!primitive) {
        const converter = definition.converter || propertyConverters.get(definition.type);
        const objDefinition = objectDefinitions.get(definition.type);

        if (converter) {
            return converter.deserialize(value);
        }

        if (objDefinition) {
            return deserialize(value, definition.type);
        }
    }
```

In my case the type is a number and as a result `primitive` is true and the converter never executed. 
The `ReverseStringConverter` is used without a 'new' in the example. Is that correct?

**Comment by edcarroll** [comment]
This should be possible yes and was a regression - I've restored this functionality in the latest version (2.2.1) which is now on npm.

**Comment by edcarroll** [comment]
Also - to address your final question, using `ReverseStringConverter` without 'new' is correct - the type of `@JsonConverter` is:

```ts
@JsonConverter(converter:IPropertyConverter | ParameterlessConstructor)
```

so it can be used without creating an instance of the converter class, so long as that class doesn't take any parameters. If it does, for example like the `BufferConverter` which takes the encoding type, then you do need to pass an instance to the decorator.

Does that all make sense? 😄

**Comment by ma-gamp** [comment]
Thank you. Works perfect now :) Love your json serializer. Makes our models much cleaner.
